// Copyright 2025 Smirnov Nikita

#ifndef ONLINE_GAME_STORE_PROJECT_ADMINISTRATOR_ADMINISTRATOR_H_
#define ONLINE_GAME_STORE_PROJECT_ADMINISTRATOR_ADMINISTRATOR_H_

#include "User.h"

class Administrator : public User {
};

#endif  // ONLINE_GAME_STORE_PROJECT_ADMINISTRATOR_ADMINISTRATOR_H_
